# Generated by Django 5.0.7 on 2024-07-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_link',
        ),
        migrations.AddField(
            model_name='parent',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
