# Generated by Django 5.0.7 on 2024-07-28 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_mobile1', models.CharField(max_length=15)),
                ('user_mobile2', models.CharField(blank=True, max_length=15, null=True)),
                ('user_mobile3', models.CharField(blank=True, max_length=15, null=True)),
                ('user_email_id', models.EmailField(max_length=254)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('payment_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_mobile_1', models.CharField(max_length=15)),
                ('school_mobile_2', models.CharField(blank=True, max_length=15, null=True)),
                ('school_mobile_3', models.CharField(blank=True, max_length=15, null=True)),
                ('school_whatsapp_number', models.CharField(max_length=15)),
                ('school_email_id', models.EmailField(max_length=254)),
                ('school_address', models.TextField()),
                ('principal_name', models.CharField(max_length=255)),
                ('principal_mobile_number', models.CharField(max_length=15)),
                ('principal_email_id', models.EmailField(max_length=254)),
                ('principal_address', models.TextField()),
                ('director_name', models.CharField(max_length=255)),
                ('director_mobile_number', models.CharField(max_length=15)),
                ('director_email_id', models.EmailField(max_length=254)),
                ('director_address', models.TextField()),
                ('dean_name', models.CharField(max_length=255)),
                ('dean_mobile_number', models.CharField(max_length=15)),
                ('dean_email_id', models.EmailField(max_length=254)),
                ('dean_address', models.TextField()),
                ('school_photo', models.ImageField(upload_to='school_photos/')),
                ('address', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=50)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_id', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.parent')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.AddField(
            model_name='parent',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('height', models.FloatField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('kid_class', models.CharField(max_length=20)),
                ('roll_number', models.IntegerField()),
                ('enrollment_number', models.IntegerField()),
                ('photo', models.ImageField(upload_to='kids_photos/')),
                ('disability', models.BooleanField(default=False)),
                ('disabled_part', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('fees_status', models.CharField(max_length=50)),
                ('monthly_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.parent')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
    ]
